### PR TITLE
Support XIAOMI MIJIA Temp and Humidity Sensor v2

### PR DESCRIPTION
**Pull request by ratcashdev**
Support for the recently announced Temp and Humidity Sensor of Xiaomi with Bluetooth and LCD display.
I did not want to duplicate all the back-end code, thus added support for an extra sensor in this package.

To be fully used, it needs a file called `site-packages/homeassistant/components/sensor/mitemp.py` that is just a slightly amended version of the miflora.py, available here: https://gist.github.com/ratcashdev/2060fd95158dacae93a80a92ae7083a4

### CODE REVIEW

**Comment by ratcashdev** [comment]
please advice how to make this code mergeable.

**Comment by ChristianKuehnel** [comment]
@ThomDietrich , @open-homeautomation 

Does it make sense to add support for the "XIAOMI MIJIA Temp and Humidity Sensor v2" into this library? From looking at the code there are quite a few similarities, but it would certainly extend the scope of this library from the plant sensors.

**Comment by ratcashdev** [comment]
IMHO, the best solution would be to extract all the back-end code into a separate package and then make both miflora and mitemp require those. I assume a lot of other sensor offering bluetooth and their implementation would benefit from a common back-end providing 3 different implementation options (bluepy, pygatt, gatttool).

**Comment by ChristianKuehnel** [comment]
@ratcashdev 
I started extracting the backend funktionality: https://github.com/ChristianKuehnel/btlewrap

This is from the current master branch, without your notification extensions...

**Comment by ratcashdev** [comment]
Lovely! Let me know when that is merged and I will submit a separate PR for the notification enhancements.

**Comment by flavio20002** [comment]
I had the same idea, but 16 days later...:-) Anyway, I would like to help. My Home assistant installation has already my version of the **mitemp_bt** Sensor (so I called it) and I've putted all in a single python file using only gatttool

**Comment by ChristianKuehnel** [comment]
@ratcashdev 
The bluetooth backend library is ready to get your notifications merged: https://github.com/ChristianKuehnel/btlewrap

And you can use it to build a new library to the Xiaomi Mijia sensors

**Comment by ratcashdev** [comment]
PR submitted: https://github.com/ChristianKuehnel/btlewrap/pull/1

**Comment by ratcashdev** [comment]
I got the mitemp implementation ready with btlewrap==0.0.2 (https://github.com/ratcashdev/mitemp)
A couple of notes though:

1. This is my very first python package, I have no account on travis, pypi, coverage, etc. I was wondering, if anyone is willing to do the publishing?
2. I am still undecided on the naming. @flavio20002 's mitemp_bt sounds better, honestly as is mitemp_ble
What do you suggest?

**Comment by flavio20002** [comment]
Hi, thank you very much. I like both names, but I prefer "bt" beacuse it's more known. Once published, I will test in my Home-asssistant. Did you update the Hass component with the right dependence (the gist version has still miflora)? Thanks

**Comment by ratcashdev** [comment]
repo and gist updated. See the readme for the gist's link. 
The new name is mitemp_bt

**Comment by ratcashdev** [comment]
so back to the publishing question: Is anyone volunteering to publish?

**Comment by ratcashdev** [comment]
All right. mitemp_bt==0.0.1 is available and can be integrated into hass using https://gist.github.com/ratcashdev/28253bb2c220788e4961f213fe87ff33

**Comment by flavio20002** [comment]
Thank you very much. Are you pllaing to PR to Home Assistant? Some notes:

- I would put a default median of 1, since the Mijia Temperature Sensor doesn't have spikes like miflora. 
- My own implementation works very good (I have used it in production for 1 month), but I always got warning in my log **Update of sensor.mijia is taking over 10 seconds** Does your implementation suffer of the same problem, or did you manage to solve it?
- I'm available to test your implementation in my environment, if you plan to make it the official Home Assistant one.
Thanks

**Comment by ratcashdev** [comment]
@flavio20002 
1. I'd rather leave it. while I haven't encountered cases when it would have spikes, batter safe than sorry
2. I am using it for more than a month. However, I can confirm, I have the same log entries like you (>10s). It seems to me that sometimes the device is too slow to respond to connection requests.
3. I am afraid i am not the one to make it official, but I will for sure create a PR.

**Comment by ratcashdev** [comment]
The PR is here https://github.com/home-assistant/home-assistant/pull/13955

**Pull request closed without merging**
