### PR TITLE
Changed formula for temperature to include negatives

### PR DESCRIPTION
**Pull request by gulasnani**

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Rationale?

**Comment by ChristianKuehnel** [comment]
@gulasnani that you for the PR. 😁

Please also add some unit test for this where you decode some byte array, you recieved from the sensor.

**Comment by gulasnani** [comment]
@ThomDietrich Really sorry for that, since I am quite a newbie.
The rationale behind using unpack is that we let python decode the string as a short signed int through the format string provided as the first argument to the function. This saves us the headache of converting the bits ourselves.
@ChristianKuehnel Sure, I will look into the testing. I checked the documentation again, and it says 'h' is for signed short int. And yeah, even I have had the opinion that it would be the easiest to use unpack for the entire string code :D

**Comment by ChristianKuehnel** [comment]
Sorry, you were right "<h" was correct.

**Comment by ChristianKuehnel** [comment]
This is for issue https://github.com/open-homeautomation/miflora/issues/49

**Comment by ChristianKuehnel** [comment]
Thx for your input. I used your code and also added tests: https://github.com/open-homeautomation/miflora/pull/65

**Pull request closed without merging**
