### PR TITLE
Use str.format, raise exception in name function

### PR DESCRIPTION
**Pull request by ThomDietrich**
Hey,

this change tackles the eminent error as can be seen in #31 (doesn't resolve the actual issue).

* name method now raises an exception when no data could be retrieved
* Unfavorable line wrapping fixed
* string building in combination with the logger was wrong. I've replaced everything with the better `str.format` method e.g.
```
OSError: [Errno Could not read data from Mi Flora sensor %s] C4:7C:8D:60:DB:A5
```

### CODE REVIEW

**Comment by ThomDietrich** [comment]
Sorry to bother you. Any issues with this PR I should be aware of? Cheers ;)

**Comment by open-homeautomation** [comment]
logging should not use string.format
lines should be no longer than 79 characters.

**Comment by ThomDietrich** [comment]
> logging should not use string.format

Okay, the bug still needs to be fixed somehow...

> lines should be no longer than 79 characters

A rather archaic length. Nowadays 120 or 160 is reasonable. Anyhow that's up to you.

**Comment by open-homeautomation** [comment]
Please create a new pull request for the fix

About line length and a lot of other style guidelines, please check the PEP8 Python style gudielines:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by ThomDietrich** [comment]
Done (#35)

I'm aware of PEP8. As I said, it's up to you.

**Pull request closed without merging**
